# Generated by Django 6.0.2 on 2026-02-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MASTER', 'Master'), ('ENCARREGADO', 'Encarregado'), ('OPERADOR', 'Operador'), ('RELATORIO', 'Relatório / Auditoria')], default='OPERADOR', max_length=20),
        ),
    ]
