# Generated by Django 6.0.2 on 2026-02-28 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('gas_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.gastype', verbose_name='Tipo de Gás')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada de Estoque (+)'), ('SAIDA', 'Saída / Venda / Retirada (-)')], max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição (Opcional)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Movimentado por')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.stock', verbose_name='Estoque Afetado')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('store', 'gas_type'), name='unique_store_gas_stock'),
        ),
    ]
